const domObjects = {
  game: '#game',
  newGameButton: '#newgame-btn',
  gameButton: '#game-button',
  gameBar: '#gamebar',
  topBorder: '#top-border',
  middleBorder: '#middle-border',
  bottomBorder: '#bottom-border',
  fieldContainer: '#field-container',
  settingsContainer: '#settings-container',
  inputRows: '#input-rows',
  inputColumns: '#input-columns',
  inputBombs: '#input-bombs',
  scores: '#scores',
  spriteClass: 'sprite',
  btnSmileyClass: 'sprite-btn-smiley',
  btnClickClass: 'sprite-btn-click',
  btnWowClass: 'sprite-btn-wow',
  btnDeadClass: 'sprite-btn-dead',
  btnCoolClass: 'sprite-btn-cool',
  flagClass: 'sprite-flag',
  fieldClass: 'sprite-blank',
  spriteBlankClass: 'sprite-blank',
  noBombClass: 'sprite-no-bomb',
  bombRedClass: 'sprite-bomb-red',
  bombClass: 'sprite-bomb-grey',
  blockClass: 'gameBlock',
  spriteBorderVerticalClass: 'sprite-border-vertical',
  clickedClass: 'clicked',
  visibleClass: 'visible',
  hiddenClass: 'hidden'
};

export default domObjects;
